/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MfaChallengeRouteImport } from './routes/mfa-challenge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingSuccessRouteImport } from './routes/billing/success'
import { Route as BillingCancelRouteImport } from './routes/billing/cancel'
import { Route as ProtectedOrganizationsRouteImport } from './routes/_protected/organizations'
import { Route as ProtectedNotificationsRouteImport } from './routes/_protected/notifications'
import { Route as ProtectedJoinRouteImport } from './routes/_protected/join'
import { Route as ProtectedAccountRouteImport } from './routes/_protected/account'
import { Route as ProtectedOrganizationIndexRouteImport } from './routes/_protected/organization/index'
import { Route as ProtectedOrganizationOrganizationIdRouteImport } from './routes/_protected/organization/$organizationId'
import { Route as ProtectedInvitationsAcceptRouteImport } from './routes/_protected/invitations/accept'
import { Route as ProtectedOrganizationOrganizationIdIndexRouteImport } from './routes/_protected/organization/$organizationId/index'
import { Route as ProtectedOrganizationOrganizationIdWebhooksRouteImport } from './routes/_protected/organization/$organizationId/webhooks'
import { Route as ProtectedOrganizationOrganizationIdSettingsRouteImport } from './routes/_protected/organization/$organizationId/settings'
import { Route as ProtectedOrganizationOrganizationIdNotificationsRouteImport } from './routes/_protected/organization/$organizationId/notifications'
import { Route as ProtectedOrganizationOrganizationIdMembersRouteImport } from './routes/_protected/organization/$organizationId/members'
import { Route as ProtectedOrganizationOrganizationIdInvitationsRouteImport } from './routes/_protected/organization/$organizationId/invitations'
import { Route as ProtectedOrganizationOrganizationIdFilesRouteImport } from './routes/_protected/organization/$organizationId/files'
import { Route as ProtectedOrganizationOrganizationIdBillingRouteImport } from './routes/_protected/organization/$organizationId/billing'
import { Route as ProtectedOrganizationOrganizationIdAuditLogRouteImport } from './routes/_protected/organization/$organizationId/audit-log'
import { Route as ProtectedOrganizationOrganizationIdPlatformIndexRouteImport } from './routes/_protected/organization/$organizationId/platform/index'
import { Route as ProtectedOrganizationOrganizationIdBillingIndexRouteImport } from './routes/_protected/organization/$organizationId/billing/index'
import { Route as ProtectedOrganizationOrganizationIdSettingsSecurityRouteImport } from './routes/_protected/organization/$organizationId/settings/security'
import { Route as ProtectedOrganizationOrganizationIdSettingsDangerRouteImport } from './routes/_protected/organization/$organizationId/settings/danger'
import { Route as ProtectedOrganizationOrganizationIdSettingsBrandingRouteImport } from './routes/_protected/organization/$organizationId/settings/branding'
import { Route as ProtectedOrganizationOrganizationIdPlatformR5RouteImport } from './routes/_protected/organization/$organizationId/platform/r5'
import { Route as ProtectedOrganizationOrganizationIdPlatformR4RouteImport } from './routes/_protected/organization/$organizationId/platform/r4'
import { Route as ProtectedOrganizationOrganizationIdPlatformR3RouteImport } from './routes/_protected/organization/$organizationId/platform/r3'
import { Route as ProtectedOrganizationOrganizationIdPlatformR2RouteImport } from './routes/_protected/organization/$organizationId/platform/r2'
import { Route as ProtectedOrganizationOrganizationIdPlatformR1RouteImport } from './routes/_protected/organization/$organizationId/platform/r1'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaChallengeRoute = MfaChallengeRouteImport.update({
  id: '/mfa-challenge',
  path: '/mfa-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCancelRoute = BillingCancelRouteImport.update({
  id: '/billing/cancel',
  path: '/billing/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOrganizationsRoute = ProtectedOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedNotificationsRoute = ProtectedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedJoinRoute = ProtectedJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrganizationIndexRoute =
  ProtectedOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOrganizationOrganizationIdRoute =
  ProtectedOrganizationOrganizationIdRouteImport.update({
    id: '/organization/$organizationId',
    path: '/organization/$organizationId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedInvitationsAcceptRoute =
  ProtectedInvitationsAcceptRouteImport.update({
    id: '/invitations/accept',
    path: '/invitations/accept',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOrganizationOrganizationIdIndexRoute =
  ProtectedOrganizationOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrganizationOrganizationIdRoute,
  } as any)
const ProtectedOrganizationOrganizationIdWebhooksRoute =
  ProtectedOrganizationOrganizationIdWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => ProtectedOrganizationOrganizationIdRoute,
  } as any)
const ProtectedOrganizationOrganizationIdSettingsRoute =
  ProtectedOrganizationOrganizationIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedOrganizationOrganizationIdRoute,
  } as any)
const ProtectedOrganizationOrganizationIdNotificationsRoute =
  ProtectedOrganizationOrganizationIdNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedOrganizationOrganizationIdRoute,
  } as any)
const ProtectedOrganizationOrganizationIdMembersRoute =
  ProtectedOrganizationOrganizationIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProtectedOrganizationOrganizationIdRoute,
  } as any)
const ProtectedOrganizationOrganizationIdInvitationsRoute =
  ProtectedOrganizationOrganizationIdInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => ProtectedOrganizationOrganizationIdRoute,
  } as any)
const ProtectedOrganizationOrganizationIdFilesRoute =
  ProtectedOrganizationOrganizationIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => ProtectedOrganizationOrganizationIdRoute,
  } as any)
const ProtectedOrganizationOrganizationIdBillingRoute =
  ProtectedOrganizationOrganizationIdBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => ProtectedOrganizationOrganizationIdRoute,
  } as any)
const ProtectedOrganizationOrganizationIdAuditLogRoute =
  ProtectedOrganizationOrganizationIdAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => ProtectedOrganizationOrganizationIdRoute,
  } as any)
const ProtectedOrganizationOrganizationIdPlatformIndexRoute =
  ProtectedOrganizationOrganizationIdPlatformIndexRouteImport.update({
    id: '/platform/',
    path: '/platform/',
    getParentRoute: () => ProtectedOrganizationOrganizationIdRoute,
  } as any)
const ProtectedOrganizationOrganizationIdBillingIndexRoute =
  ProtectedOrganizationOrganizationIdBillingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrganizationOrganizationIdBillingRoute,
  } as any)
const ProtectedOrganizationOrganizationIdSettingsSecurityRoute =
  ProtectedOrganizationOrganizationIdSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => ProtectedOrganizationOrganizationIdSettingsRoute,
  } as any)
const ProtectedOrganizationOrganizationIdSettingsDangerRoute =
  ProtectedOrganizationOrganizationIdSettingsDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => ProtectedOrganizationOrganizationIdSettingsRoute,
  } as any)
const ProtectedOrganizationOrganizationIdSettingsBrandingRoute =
  ProtectedOrganizationOrganizationIdSettingsBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => ProtectedOrganizationOrganizationIdSettingsRoute,
  } as any)
const ProtectedOrganizationOrganizationIdPlatformR5Route =
  ProtectedOrganizationOrganizationIdPlatformR5RouteImport.update({
    id: '/platform/r5',
    path: '/platform/r5',
    getParentRoute: () => ProtectedOrganizationOrganizationIdRoute,
  } as any)
const ProtectedOrganizationOrganizationIdPlatformR4Route =
  ProtectedOrganizationOrganizationIdPlatformR4RouteImport.update({
    id: '/platform/r4',
    path: '/platform/r4',
    getParentRoute: () => ProtectedOrganizationOrganizationIdRoute,
  } as any)
const ProtectedOrganizationOrganizationIdPlatformR3Route =
  ProtectedOrganizationOrganizationIdPlatformR3RouteImport.update({
    id: '/platform/r3',
    path: '/platform/r3',
    getParentRoute: () => ProtectedOrganizationOrganizationIdRoute,
  } as any)
const ProtectedOrganizationOrganizationIdPlatformR2Route =
  ProtectedOrganizationOrganizationIdPlatformR2RouteImport.update({
    id: '/platform/r2',
    path: '/platform/r2',
    getParentRoute: () => ProtectedOrganizationOrganizationIdRoute,
  } as any)
const ProtectedOrganizationOrganizationIdPlatformR1Route =
  ProtectedOrganizationOrganizationIdPlatformR1RouteImport.update({
    id: '/platform/r1',
    path: '/platform/r1',
    getParentRoute: () => ProtectedOrganizationOrganizationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof ProtectedAccountRoute
  '/join': typeof ProtectedJoinRoute
  '/notifications': typeof ProtectedNotificationsRoute
  '/organizations': typeof ProtectedOrganizationsRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/invitations/accept': typeof ProtectedInvitationsAcceptRoute
  '/organization/$organizationId': typeof ProtectedOrganizationOrganizationIdRouteWithChildren
  '/organization/': typeof ProtectedOrganizationIndexRoute
  '/organization/$organizationId/audit-log': typeof ProtectedOrganizationOrganizationIdAuditLogRoute
  '/organization/$organizationId/billing': typeof ProtectedOrganizationOrganizationIdBillingRouteWithChildren
  '/organization/$organizationId/files': typeof ProtectedOrganizationOrganizationIdFilesRoute
  '/organization/$organizationId/invitations': typeof ProtectedOrganizationOrganizationIdInvitationsRoute
  '/organization/$organizationId/members': typeof ProtectedOrganizationOrganizationIdMembersRoute
  '/organization/$organizationId/notifications': typeof ProtectedOrganizationOrganizationIdNotificationsRoute
  '/organization/$organizationId/settings': typeof ProtectedOrganizationOrganizationIdSettingsRouteWithChildren
  '/organization/$organizationId/webhooks': typeof ProtectedOrganizationOrganizationIdWebhooksRoute
  '/organization/$organizationId/': typeof ProtectedOrganizationOrganizationIdIndexRoute
  '/organization/$organizationId/platform/r1': typeof ProtectedOrganizationOrganizationIdPlatformR1Route
  '/organization/$organizationId/platform/r2': typeof ProtectedOrganizationOrganizationIdPlatformR2Route
  '/organization/$organizationId/platform/r3': typeof ProtectedOrganizationOrganizationIdPlatformR3Route
  '/organization/$organizationId/platform/r4': typeof ProtectedOrganizationOrganizationIdPlatformR4Route
  '/organization/$organizationId/platform/r5': typeof ProtectedOrganizationOrganizationIdPlatformR5Route
  '/organization/$organizationId/settings/branding': typeof ProtectedOrganizationOrganizationIdSettingsBrandingRoute
  '/organization/$organizationId/settings/danger': typeof ProtectedOrganizationOrganizationIdSettingsDangerRoute
  '/organization/$organizationId/settings/security': typeof ProtectedOrganizationOrganizationIdSettingsSecurityRoute
  '/organization/$organizationId/billing/': typeof ProtectedOrganizationOrganizationIdBillingIndexRoute
  '/organization/$organizationId/platform/': typeof ProtectedOrganizationOrganizationIdPlatformIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof ProtectedAccountRoute
  '/join': typeof ProtectedJoinRoute
  '/notifications': typeof ProtectedNotificationsRoute
  '/organizations': typeof ProtectedOrganizationsRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/invitations/accept': typeof ProtectedInvitationsAcceptRoute
  '/organization': typeof ProtectedOrganizationIndexRoute
  '/organization/$organizationId/audit-log': typeof ProtectedOrganizationOrganizationIdAuditLogRoute
  '/organization/$organizationId/files': typeof ProtectedOrganizationOrganizationIdFilesRoute
  '/organization/$organizationId/invitations': typeof ProtectedOrganizationOrganizationIdInvitationsRoute
  '/organization/$organizationId/members': typeof ProtectedOrganizationOrganizationIdMembersRoute
  '/organization/$organizationId/notifications': typeof ProtectedOrganizationOrganizationIdNotificationsRoute
  '/organization/$organizationId/settings': typeof ProtectedOrganizationOrganizationIdSettingsRouteWithChildren
  '/organization/$organizationId/webhooks': typeof ProtectedOrganizationOrganizationIdWebhooksRoute
  '/organization/$organizationId': typeof ProtectedOrganizationOrganizationIdIndexRoute
  '/organization/$organizationId/platform/r1': typeof ProtectedOrganizationOrganizationIdPlatformR1Route
  '/organization/$organizationId/platform/r2': typeof ProtectedOrganizationOrganizationIdPlatformR2Route
  '/organization/$organizationId/platform/r3': typeof ProtectedOrganizationOrganizationIdPlatformR3Route
  '/organization/$organizationId/platform/r4': typeof ProtectedOrganizationOrganizationIdPlatformR4Route
  '/organization/$organizationId/platform/r5': typeof ProtectedOrganizationOrganizationIdPlatformR5Route
  '/organization/$organizationId/settings/branding': typeof ProtectedOrganizationOrganizationIdSettingsBrandingRoute
  '/organization/$organizationId/settings/danger': typeof ProtectedOrganizationOrganizationIdSettingsDangerRoute
  '/organization/$organizationId/settings/security': typeof ProtectedOrganizationOrganizationIdSettingsSecurityRoute
  '/organization/$organizationId/billing': typeof ProtectedOrganizationOrganizationIdBillingIndexRoute
  '/organization/$organizationId/platform': typeof ProtectedOrganizationOrganizationIdPlatformIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_protected/account': typeof ProtectedAccountRoute
  '/_protected/join': typeof ProtectedJoinRoute
  '/_protected/notifications': typeof ProtectedNotificationsRoute
  '/_protected/organizations': typeof ProtectedOrganizationsRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/_protected/invitations/accept': typeof ProtectedInvitationsAcceptRoute
  '/_protected/organization/$organizationId': typeof ProtectedOrganizationOrganizationIdRouteWithChildren
  '/_protected/organization/': typeof ProtectedOrganizationIndexRoute
  '/_protected/organization/$organizationId/audit-log': typeof ProtectedOrganizationOrganizationIdAuditLogRoute
  '/_protected/organization/$organizationId/billing': typeof ProtectedOrganizationOrganizationIdBillingRouteWithChildren
  '/_protected/organization/$organizationId/files': typeof ProtectedOrganizationOrganizationIdFilesRoute
  '/_protected/organization/$organizationId/invitations': typeof ProtectedOrganizationOrganizationIdInvitationsRoute
  '/_protected/organization/$organizationId/members': typeof ProtectedOrganizationOrganizationIdMembersRoute
  '/_protected/organization/$organizationId/notifications': typeof ProtectedOrganizationOrganizationIdNotificationsRoute
  '/_protected/organization/$organizationId/settings': typeof ProtectedOrganizationOrganizationIdSettingsRouteWithChildren
  '/_protected/organization/$organizationId/webhooks': typeof ProtectedOrganizationOrganizationIdWebhooksRoute
  '/_protected/organization/$organizationId/': typeof ProtectedOrganizationOrganizationIdIndexRoute
  '/_protected/organization/$organizationId/platform/r1': typeof ProtectedOrganizationOrganizationIdPlatformR1Route
  '/_protected/organization/$organizationId/platform/r2': typeof ProtectedOrganizationOrganizationIdPlatformR2Route
  '/_protected/organization/$organizationId/platform/r3': typeof ProtectedOrganizationOrganizationIdPlatformR3Route
  '/_protected/organization/$organizationId/platform/r4': typeof ProtectedOrganizationOrganizationIdPlatformR4Route
  '/_protected/organization/$organizationId/platform/r5': typeof ProtectedOrganizationOrganizationIdPlatformR5Route
  '/_protected/organization/$organizationId/settings/branding': typeof ProtectedOrganizationOrganizationIdSettingsBrandingRoute
  '/_protected/organization/$organizationId/settings/danger': typeof ProtectedOrganizationOrganizationIdSettingsDangerRoute
  '/_protected/organization/$organizationId/settings/security': typeof ProtectedOrganizationOrganizationIdSettingsSecurityRoute
  '/_protected/organization/$organizationId/billing/': typeof ProtectedOrganizationOrganizationIdBillingIndexRoute
  '/_protected/organization/$organizationId/platform/': typeof ProtectedOrganizationOrganizationIdPlatformIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/mfa-challenge'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/account'
    | '/join'
    | '/notifications'
    | '/organizations'
    | '/billing/cancel'
    | '/billing/success'
    | '/invitations/accept'
    | '/organization/$organizationId'
    | '/organization/'
    | '/organization/$organizationId/audit-log'
    | '/organization/$organizationId/billing'
    | '/organization/$organizationId/files'
    | '/organization/$organizationId/invitations'
    | '/organization/$organizationId/members'
    | '/organization/$organizationId/notifications'
    | '/organization/$organizationId/settings'
    | '/organization/$organizationId/webhooks'
    | '/organization/$organizationId/'
    | '/organization/$organizationId/platform/r1'
    | '/organization/$organizationId/platform/r2'
    | '/organization/$organizationId/platform/r3'
    | '/organization/$organizationId/platform/r4'
    | '/organization/$organizationId/platform/r5'
    | '/organization/$organizationId/settings/branding'
    | '/organization/$organizationId/settings/danger'
    | '/organization/$organizationId/settings/security'
    | '/organization/$organizationId/billing/'
    | '/organization/$organizationId/platform/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/mfa-challenge'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/account'
    | '/join'
    | '/notifications'
    | '/organizations'
    | '/billing/cancel'
    | '/billing/success'
    | '/invitations/accept'
    | '/organization'
    | '/organization/$organizationId/audit-log'
    | '/organization/$organizationId/files'
    | '/organization/$organizationId/invitations'
    | '/organization/$organizationId/members'
    | '/organization/$organizationId/notifications'
    | '/organization/$organizationId/settings'
    | '/organization/$organizationId/webhooks'
    | '/organization/$organizationId'
    | '/organization/$organizationId/platform/r1'
    | '/organization/$organizationId/platform/r2'
    | '/organization/$organizationId/platform/r3'
    | '/organization/$organizationId/platform/r4'
    | '/organization/$organizationId/platform/r5'
    | '/organization/$organizationId/settings/branding'
    | '/organization/$organizationId/settings/danger'
    | '/organization/$organizationId/settings/security'
    | '/organization/$organizationId/billing'
    | '/organization/$organizationId/platform'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/forgot-password'
    | '/login'
    | '/mfa-challenge'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/_protected/account'
    | '/_protected/join'
    | '/_protected/notifications'
    | '/_protected/organizations'
    | '/billing/cancel'
    | '/billing/success'
    | '/_protected/invitations/accept'
    | '/_protected/organization/$organizationId'
    | '/_protected/organization/'
    | '/_protected/organization/$organizationId/audit-log'
    | '/_protected/organization/$organizationId/billing'
    | '/_protected/organization/$organizationId/files'
    | '/_protected/organization/$organizationId/invitations'
    | '/_protected/organization/$organizationId/members'
    | '/_protected/organization/$organizationId/notifications'
    | '/_protected/organization/$organizationId/settings'
    | '/_protected/organization/$organizationId/webhooks'
    | '/_protected/organization/$organizationId/'
    | '/_protected/organization/$organizationId/platform/r1'
    | '/_protected/organization/$organizationId/platform/r2'
    | '/_protected/organization/$organizationId/platform/r3'
    | '/_protected/organization/$organizationId/platform/r4'
    | '/_protected/organization/$organizationId/platform/r5'
    | '/_protected/organization/$organizationId/settings/branding'
    | '/_protected/organization/$organizationId/settings/danger'
    | '/_protected/organization/$organizationId/settings/security'
    | '/_protected/organization/$organizationId/billing/'
    | '/_protected/organization/$organizationId/platform/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MfaChallengeRoute: typeof MfaChallengeRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  BillingCancelRoute: typeof BillingCancelRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa-challenge': {
      id: '/mfa-challenge'
      path: '/mfa-challenge'
      fullPath: '/mfa-challenge'
      preLoaderRoute: typeof MfaChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/cancel': {
      id: '/billing/cancel'
      path: '/billing/cancel'
      fullPath: '/billing/cancel'
      preLoaderRoute: typeof BillingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/organizations': {
      id: '/_protected/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof ProtectedOrganizationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/notifications': {
      id: '/_protected/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ProtectedNotificationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/join': {
      id: '/_protected/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof ProtectedJoinRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organization/': {
      id: '/_protected/organization/'
      path: '/organization'
      fullPath: '/organization/'
      preLoaderRoute: typeof ProtectedOrganizationIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organization/$organizationId': {
      id: '/_protected/organization/$organizationId'
      path: '/organization/$organizationId'
      fullPath: '/organization/$organizationId'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/invitations/accept': {
      id: '/_protected/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof ProtectedInvitationsAcceptRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organization/$organizationId/': {
      id: '/_protected/organization/$organizationId/'
      path: '/'
      fullPath: '/organization/$organizationId/'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdIndexRouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdRoute
    }
    '/_protected/organization/$organizationId/webhooks': {
      id: '/_protected/organization/$organizationId/webhooks'
      path: '/webhooks'
      fullPath: '/organization/$organizationId/webhooks'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdWebhooksRouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdRoute
    }
    '/_protected/organization/$organizationId/settings': {
      id: '/_protected/organization/$organizationId/settings'
      path: '/settings'
      fullPath: '/organization/$organizationId/settings'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdSettingsRouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdRoute
    }
    '/_protected/organization/$organizationId/notifications': {
      id: '/_protected/organization/$organizationId/notifications'
      path: '/notifications'
      fullPath: '/organization/$organizationId/notifications'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdNotificationsRouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdRoute
    }
    '/_protected/organization/$organizationId/members': {
      id: '/_protected/organization/$organizationId/members'
      path: '/members'
      fullPath: '/organization/$organizationId/members'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdMembersRouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdRoute
    }
    '/_protected/organization/$organizationId/invitations': {
      id: '/_protected/organization/$organizationId/invitations'
      path: '/invitations'
      fullPath: '/organization/$organizationId/invitations'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdInvitationsRouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdRoute
    }
    '/_protected/organization/$organizationId/files': {
      id: '/_protected/organization/$organizationId/files'
      path: '/files'
      fullPath: '/organization/$organizationId/files'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdFilesRouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdRoute
    }
    '/_protected/organization/$organizationId/billing': {
      id: '/_protected/organization/$organizationId/billing'
      path: '/billing'
      fullPath: '/organization/$organizationId/billing'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdBillingRouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdRoute
    }
    '/_protected/organization/$organizationId/audit-log': {
      id: '/_protected/organization/$organizationId/audit-log'
      path: '/audit-log'
      fullPath: '/organization/$organizationId/audit-log'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdAuditLogRouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdRoute
    }
    '/_protected/organization/$organizationId/platform/': {
      id: '/_protected/organization/$organizationId/platform/'
      path: '/platform'
      fullPath: '/organization/$organizationId/platform/'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdPlatformIndexRouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdRoute
    }
    '/_protected/organization/$organizationId/billing/': {
      id: '/_protected/organization/$organizationId/billing/'
      path: '/'
      fullPath: '/organization/$organizationId/billing/'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdBillingIndexRouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdBillingRoute
    }
    '/_protected/organization/$organizationId/settings/security': {
      id: '/_protected/organization/$organizationId/settings/security'
      path: '/security'
      fullPath: '/organization/$organizationId/settings/security'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdSettingsSecurityRouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdSettingsRoute
    }
    '/_protected/organization/$organizationId/settings/danger': {
      id: '/_protected/organization/$organizationId/settings/danger'
      path: '/danger'
      fullPath: '/organization/$organizationId/settings/danger'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdSettingsDangerRouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdSettingsRoute
    }
    '/_protected/organization/$organizationId/settings/branding': {
      id: '/_protected/organization/$organizationId/settings/branding'
      path: '/branding'
      fullPath: '/organization/$organizationId/settings/branding'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdSettingsBrandingRouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdSettingsRoute
    }
    '/_protected/organization/$organizationId/platform/r5': {
      id: '/_protected/organization/$organizationId/platform/r5'
      path: '/platform/r5'
      fullPath: '/organization/$organizationId/platform/r5'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdPlatformR5RouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdRoute
    }
    '/_protected/organization/$organizationId/platform/r4': {
      id: '/_protected/organization/$organizationId/platform/r4'
      path: '/platform/r4'
      fullPath: '/organization/$organizationId/platform/r4'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdPlatformR4RouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdRoute
    }
    '/_protected/organization/$organizationId/platform/r3': {
      id: '/_protected/organization/$organizationId/platform/r3'
      path: '/platform/r3'
      fullPath: '/organization/$organizationId/platform/r3'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdPlatformR3RouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdRoute
    }
    '/_protected/organization/$organizationId/platform/r2': {
      id: '/_protected/organization/$organizationId/platform/r2'
      path: '/platform/r2'
      fullPath: '/organization/$organizationId/platform/r2'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdPlatformR2RouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdRoute
    }
    '/_protected/organization/$organizationId/platform/r1': {
      id: '/_protected/organization/$organizationId/platform/r1'
      path: '/platform/r1'
      fullPath: '/organization/$organizationId/platform/r1'
      preLoaderRoute: typeof ProtectedOrganizationOrganizationIdPlatformR1RouteImport
      parentRoute: typeof ProtectedOrganizationOrganizationIdRoute
    }
  }
}

interface ProtectedOrganizationOrganizationIdBillingRouteChildren {
  ProtectedOrganizationOrganizationIdBillingIndexRoute: typeof ProtectedOrganizationOrganizationIdBillingIndexRoute
}

const ProtectedOrganizationOrganizationIdBillingRouteChildren: ProtectedOrganizationOrganizationIdBillingRouteChildren =
  {
    ProtectedOrganizationOrganizationIdBillingIndexRoute:
      ProtectedOrganizationOrganizationIdBillingIndexRoute,
  }

const ProtectedOrganizationOrganizationIdBillingRouteWithChildren =
  ProtectedOrganizationOrganizationIdBillingRoute._addFileChildren(
    ProtectedOrganizationOrganizationIdBillingRouteChildren,
  )

interface ProtectedOrganizationOrganizationIdSettingsRouteChildren {
  ProtectedOrganizationOrganizationIdSettingsBrandingRoute: typeof ProtectedOrganizationOrganizationIdSettingsBrandingRoute
  ProtectedOrganizationOrganizationIdSettingsDangerRoute: typeof ProtectedOrganizationOrganizationIdSettingsDangerRoute
  ProtectedOrganizationOrganizationIdSettingsSecurityRoute: typeof ProtectedOrganizationOrganizationIdSettingsSecurityRoute
}

const ProtectedOrganizationOrganizationIdSettingsRouteChildren: ProtectedOrganizationOrganizationIdSettingsRouteChildren =
  {
    ProtectedOrganizationOrganizationIdSettingsBrandingRoute:
      ProtectedOrganizationOrganizationIdSettingsBrandingRoute,
    ProtectedOrganizationOrganizationIdSettingsDangerRoute:
      ProtectedOrganizationOrganizationIdSettingsDangerRoute,
    ProtectedOrganizationOrganizationIdSettingsSecurityRoute:
      ProtectedOrganizationOrganizationIdSettingsSecurityRoute,
  }

const ProtectedOrganizationOrganizationIdSettingsRouteWithChildren =
  ProtectedOrganizationOrganizationIdSettingsRoute._addFileChildren(
    ProtectedOrganizationOrganizationIdSettingsRouteChildren,
  )

interface ProtectedOrganizationOrganizationIdRouteChildren {
  ProtectedOrganizationOrganizationIdAuditLogRoute: typeof ProtectedOrganizationOrganizationIdAuditLogRoute
  ProtectedOrganizationOrganizationIdBillingRoute: typeof ProtectedOrganizationOrganizationIdBillingRouteWithChildren
  ProtectedOrganizationOrganizationIdFilesRoute: typeof ProtectedOrganizationOrganizationIdFilesRoute
  ProtectedOrganizationOrganizationIdInvitationsRoute: typeof ProtectedOrganizationOrganizationIdInvitationsRoute
  ProtectedOrganizationOrganizationIdMembersRoute: typeof ProtectedOrganizationOrganizationIdMembersRoute
  ProtectedOrganizationOrganizationIdNotificationsRoute: typeof ProtectedOrganizationOrganizationIdNotificationsRoute
  ProtectedOrganizationOrganizationIdSettingsRoute: typeof ProtectedOrganizationOrganizationIdSettingsRouteWithChildren
  ProtectedOrganizationOrganizationIdWebhooksRoute: typeof ProtectedOrganizationOrganizationIdWebhooksRoute
  ProtectedOrganizationOrganizationIdIndexRoute: typeof ProtectedOrganizationOrganizationIdIndexRoute
  ProtectedOrganizationOrganizationIdPlatformR1Route: typeof ProtectedOrganizationOrganizationIdPlatformR1Route
  ProtectedOrganizationOrganizationIdPlatformR2Route: typeof ProtectedOrganizationOrganizationIdPlatformR2Route
  ProtectedOrganizationOrganizationIdPlatformR3Route: typeof ProtectedOrganizationOrganizationIdPlatformR3Route
  ProtectedOrganizationOrganizationIdPlatformR4Route: typeof ProtectedOrganizationOrganizationIdPlatformR4Route
  ProtectedOrganizationOrganizationIdPlatformR5Route: typeof ProtectedOrganizationOrganizationIdPlatformR5Route
  ProtectedOrganizationOrganizationIdPlatformIndexRoute: typeof ProtectedOrganizationOrganizationIdPlatformIndexRoute
}

const ProtectedOrganizationOrganizationIdRouteChildren: ProtectedOrganizationOrganizationIdRouteChildren =
  {
    ProtectedOrganizationOrganizationIdAuditLogRoute:
      ProtectedOrganizationOrganizationIdAuditLogRoute,
    ProtectedOrganizationOrganizationIdBillingRoute:
      ProtectedOrganizationOrganizationIdBillingRouteWithChildren,
    ProtectedOrganizationOrganizationIdFilesRoute:
      ProtectedOrganizationOrganizationIdFilesRoute,
    ProtectedOrganizationOrganizationIdInvitationsRoute:
      ProtectedOrganizationOrganizationIdInvitationsRoute,
    ProtectedOrganizationOrganizationIdMembersRoute:
      ProtectedOrganizationOrganizationIdMembersRoute,
    ProtectedOrganizationOrganizationIdNotificationsRoute:
      ProtectedOrganizationOrganizationIdNotificationsRoute,
    ProtectedOrganizationOrganizationIdSettingsRoute:
      ProtectedOrganizationOrganizationIdSettingsRouteWithChildren,
    ProtectedOrganizationOrganizationIdWebhooksRoute:
      ProtectedOrganizationOrganizationIdWebhooksRoute,
    ProtectedOrganizationOrganizationIdIndexRoute:
      ProtectedOrganizationOrganizationIdIndexRoute,
    ProtectedOrganizationOrganizationIdPlatformR1Route:
      ProtectedOrganizationOrganizationIdPlatformR1Route,
    ProtectedOrganizationOrganizationIdPlatformR2Route:
      ProtectedOrganizationOrganizationIdPlatformR2Route,
    ProtectedOrganizationOrganizationIdPlatformR3Route:
      ProtectedOrganizationOrganizationIdPlatformR3Route,
    ProtectedOrganizationOrganizationIdPlatformR4Route:
      ProtectedOrganizationOrganizationIdPlatformR4Route,
    ProtectedOrganizationOrganizationIdPlatformR5Route:
      ProtectedOrganizationOrganizationIdPlatformR5Route,
    ProtectedOrganizationOrganizationIdPlatformIndexRoute:
      ProtectedOrganizationOrganizationIdPlatformIndexRoute,
  }

const ProtectedOrganizationOrganizationIdRouteWithChildren =
  ProtectedOrganizationOrganizationIdRoute._addFileChildren(
    ProtectedOrganizationOrganizationIdRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedAccountRoute: typeof ProtectedAccountRoute
  ProtectedJoinRoute: typeof ProtectedJoinRoute
  ProtectedNotificationsRoute: typeof ProtectedNotificationsRoute
  ProtectedOrganizationsRoute: typeof ProtectedOrganizationsRoute
  ProtectedInvitationsAcceptRoute: typeof ProtectedInvitationsAcceptRoute
  ProtectedOrganizationOrganizationIdRoute: typeof ProtectedOrganizationOrganizationIdRouteWithChildren
  ProtectedOrganizationIndexRoute: typeof ProtectedOrganizationIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountRoute: ProtectedAccountRoute,
  ProtectedJoinRoute: ProtectedJoinRoute,
  ProtectedNotificationsRoute: ProtectedNotificationsRoute,
  ProtectedOrganizationsRoute: ProtectedOrganizationsRoute,
  ProtectedInvitationsAcceptRoute: ProtectedInvitationsAcceptRoute,
  ProtectedOrganizationOrganizationIdRoute:
    ProtectedOrganizationOrganizationIdRouteWithChildren,
  ProtectedOrganizationIndexRoute: ProtectedOrganizationIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MfaChallengeRoute: MfaChallengeRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  BillingCancelRoute: BillingCancelRoute,
  BillingSuccessRoute: BillingSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
