CREATE SCHEMA IF NOT EXISTS ref;

CREATE TABLE ref.currencies (
    code           TEXT        PRIMARY KEY,
    name           TEXT        NOT NULL,
    symbol         TEXT        NOT NULL DEFAULT '',
    decimal_places SMALLINT    NOT NULL DEFAULT 2,
    active         BOOLEAN     NOT NULL DEFAULT true,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE ref.countries (
    code          TEXT        PRIMARY KEY,
    name          TEXT        NOT NULL,
    phone_code    TEXT        NOT NULL DEFAULT '',
    currency_code TEXT        NOT NULL REFERENCES ref.currencies(code),
    tax_rate_bps  INT         NOT NULL DEFAULT 0,
    active        BOOLEAN     NOT NULL DEFAULT true,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Curated currency seed: the 10 most globally-used currencies plus every
-- ASEAN/SEA currency (this product's primary region), 19 total. Only USD
-- (global) and IDR (primary market) start active — everything else is a
-- disabled placeholder, flip `active` in Studio when the business expands
-- into that currency. Deliberately NOT a full ISO 4217 list — any country below
-- whose real currency isn't one of these 19 is seeded with `currency_code='USD'`
-- instead (flagged, not its true currency) to keep the FK satisfied without
-- bloating this table; correct it in Studio if that market is activated.
INSERT INTO ref.currencies (code, name, symbol, decimal_places, active) VALUES
    ('USD', 'US Dollar', '$', 2, true),
    ('EUR', 'Euro', '€', 2, false),
    ('JPY', 'Japanese Yen', '¥', 0, false),
    ('GBP', 'British Pound', '£', 2, false),
    ('CNY', 'Chinese Yuan', '¥', 2, false),
    ('AUD', 'Australian Dollar', '$', 2, false),
    ('CAD', 'Canadian Dollar', '$', 2, false),
    ('CHF', 'Swiss Franc', 'CHF', 2, false),
    ('HKD', 'Hong Kong Dollar', '$', 2, false),
    ('SGD', 'Singapore Dollar', '$', 2, false),
    ('IDR', 'Indonesian Rupiah', 'Rp', 0, true),
    ('THB', 'Thai Baht', '฿', 2, false),
    ('MYR', 'Malaysian Ringgit', 'RM', 2, false),
    ('PHP', 'Philippine Peso', '₱', 2, false),
    ('VND', 'Vietnamese Dong', '₫', 0, false),
    ('BND', 'Brunei Dollar', '$', 2, false),
    ('MMK', 'Myanmar Kyat', 'K', 2, false),
    ('KHR', 'Cambodian Riel', '៛', 2, false),
    ('LAK', 'Lao Kip', '₭', 2, false);

-- Full ISO 3166-1 seed (UN member states + Vatican + Palestine, standard
-- reference data) so operators can activate a new market from Studio without
-- adding a country row first. Only Indonesia (ID) starts active. Countries
-- whose real currency isn't in the 19-row set above use the same
-- currency_code='USD' placeholder convention described above. Hand-compiled
-- — verify against an authoritative ISO 3166-1 source before relying on it.
INSERT INTO ref.countries (code, name, phone_code, currency_code, active) VALUES
    ('ID', 'Indonesia', '+62', 'IDR', true),
    ('US', 'United States', '+1', 'USD', false),
    ('GB', 'United Kingdom', '+44', 'GBP', false),
    ('DE', 'Germany', '+49', 'EUR', false),
    ('FR', 'France', '+33', 'EUR', false),
    ('IT', 'Italy', '+39', 'EUR', false),
    ('ES', 'Spain', '+34', 'EUR', false),
    ('PT', 'Portugal', '+351', 'EUR', false),
    ('NL', 'Netherlands', '+31', 'EUR', false),
    ('BE', 'Belgium', '+32', 'EUR', false),
    ('LU', 'Luxembourg', '+352', 'EUR', false),
    ('IE', 'Ireland', '+353', 'EUR', false),
    ('CH', 'Switzerland', '+41', 'CHF', false),
    ('AT', 'Austria', '+43', 'EUR', false),
    ('SE', 'Sweden', '+46', 'USD', false),
    ('NO', 'Norway', '+47', 'USD', false),
    ('DK', 'Denmark', '+45', 'USD', false),
    ('FI', 'Finland', '+358', 'EUR', false),
    ('IS', 'Iceland', '+354', 'USD', false),
    ('PL', 'Poland', '+48', 'USD', false),
    ('CZ', 'Czechia', '+420', 'USD', false),
    ('SK', 'Slovakia', '+421', 'EUR', false),
    ('HU', 'Hungary', '+36', 'USD', false),
    ('RO', 'Romania', '+40', 'USD', false),
    ('BG', 'Bulgaria', '+359', 'USD', false),
    ('GR', 'Greece', '+30', 'EUR', false),
    ('HR', 'Croatia', '+385', 'EUR', false),
    ('SI', 'Slovenia', '+386', 'EUR', false),
    ('RS', 'Serbia', '+381', 'USD', false),
    ('AL', 'Albania', '+355', 'USD', false),
    ('MK', 'North Macedonia', '+389', 'USD', false),
    ('BA', 'Bosnia and Herzegovina', '+387', 'USD', false),
    ('ME', 'Montenegro', '+382', 'EUR', false),
    ('XK', 'Kosovo', '+383', 'EUR', false),
    ('MD', 'Moldova', '+373', 'USD', false),
    ('UA', 'Ukraine', '+380', 'USD', false),
    ('BY', 'Belarus', '+375', 'USD', false),
    ('RU', 'Russia', '+7', 'USD', false),
    ('GE', 'Georgia', '+995', 'USD', false),
    ('AM', 'Armenia', '+374', 'USD', false),
    ('AZ', 'Azerbaijan', '+994', 'USD', false),
    ('EE', 'Estonia', '+372', 'EUR', false),
    ('LV', 'Latvia', '+371', 'EUR', false),
    ('LT', 'Lithuania', '+370', 'EUR', false),
    ('MT', 'Malta', '+356', 'EUR', false),
    ('CY', 'Cyprus', '+357', 'EUR', false),
    ('AD', 'Andorra', '+376', 'EUR', false),
    ('MC', 'Monaco', '+377', 'EUR', false),
    ('SM', 'San Marino', '+378', 'EUR', false),
    ('VA', 'Vatican City', '+379', 'EUR', false),
    ('LI', 'Liechtenstein', '+423', 'CHF', false),
    ('CN', 'China', '+86', 'CNY', false),
    ('JP', 'Japan', '+81', 'JPY', false),
    ('KR', 'South Korea', '+82', 'USD', false),
    ('KP', 'North Korea', '+850', 'USD', false),
    ('MN', 'Mongolia', '+976', 'USD', false),
    ('TW', 'Taiwan', '+886', 'USD', false),
    ('HK', 'Hong Kong', '+852', 'HKD', false),
    ('MO', 'Macao', '+853', 'USD', false),
    ('MY', 'Malaysia', '+60', 'MYR', false),
    ('SG', 'Singapore', '+65', 'SGD', false),
    ('TH', 'Thailand', '+66', 'THB', false),
    ('VN', 'Vietnam', '+84', 'VND', false),
    ('PH', 'Philippines', '+63', 'PHP', false),
    ('KH', 'Cambodia', '+855', 'KHR', false),
    ('LA', 'Laos', '+856', 'LAK', false),
    ('MM', 'Myanmar', '+95', 'MMK', false),
    ('BN', 'Brunei', '+673', 'BND', false),
    ('TL', 'Timor-Leste', '+670', 'USD', false),
    ('IN', 'India', '+91', 'USD', false),
    ('PK', 'Pakistan', '+92', 'USD', false),
    ('BD', 'Bangladesh', '+880', 'USD', false),
    ('LK', 'Sri Lanka', '+94', 'USD', false),
    ('NP', 'Nepal', '+977', 'USD', false),
    ('BT', 'Bhutan', '+975', 'USD', false),
    ('MV', 'Maldives', '+960', 'USD', false),
    ('AF', 'Afghanistan', '+93', 'USD', false),
    ('KZ', 'Kazakhstan', '+7', 'USD', false),
    ('UZ', 'Uzbekistan', '+998', 'USD', false),
    ('KG', 'Kyrgyzstan', '+996', 'USD', false),
    ('TJ', 'Tajikistan', '+992', 'USD', false),
    ('TM', 'Turkmenistan', '+993', 'USD', false),
    ('AE', 'United Arab Emirates', '+971', 'USD', false),
    ('SA', 'Saudi Arabia', '+966', 'USD', false),
    ('QA', 'Qatar', '+974', 'USD', false),
    ('KW', 'Kuwait', '+965', 'USD', false),
    ('BH', 'Bahrain', '+973', 'USD', false),
    ('OM', 'Oman', '+968', 'USD', false),
    ('JO', 'Jordan', '+962', 'USD', false),
    ('IL', 'Israel', '+972', 'USD', false),
    ('PS', 'Palestine', '+970', 'USD', false),
    ('LB', 'Lebanon', '+961', 'USD', false),
    ('SY', 'Syria', '+963', 'USD', false),
    ('IQ', 'Iraq', '+964', 'USD', false),
    ('IR', 'Iran', '+98', 'USD', false),
    ('YE', 'Yemen', '+967', 'USD', false),
    ('TR', 'Turkiye', '+90', 'USD', false),
    ('ZA', 'South Africa', '+27', 'USD', false),
    ('NG', 'Nigeria', '+234', 'USD', false),
    ('EG', 'Egypt', '+20', 'USD', false),
    ('KE', 'Kenya', '+254', 'USD', false),
    ('GH', 'Ghana', '+233', 'USD', false),
    ('TZ', 'Tanzania', '+255', 'USD', false),
    ('UG', 'Uganda', '+256', 'USD', false),
    ('DZ', 'Algeria', '+213', 'USD', false),
    ('MA', 'Morocco', '+212', 'USD', false),
    ('TN', 'Tunisia', '+216', 'USD', false),
    ('LY', 'Libya', '+218', 'USD', false),
    ('ET', 'Ethiopia', '+251', 'USD', false),
    ('SD', 'Sudan', '+249', 'USD', false),
    ('SS', 'South Sudan', '+211', 'USD', false),
    ('SN', 'Senegal', '+221', 'USD', false),
    ('CI', 'Cote d''Ivoire', '+225', 'USD', false),
    ('ML', 'Mali', '+223', 'USD', false),
    ('BF', 'Burkina Faso', '+226', 'USD', false),
    ('NE', 'Niger', '+227', 'USD', false),
    ('TG', 'Togo', '+228', 'USD', false),
    ('BJ', 'Benin', '+229', 'USD', false),
    ('GW', 'Guinea-Bissau', '+245', 'USD', false),
    ('CM', 'Cameroon', '+237', 'USD', false),
    ('GA', 'Gabon', '+241', 'USD', false),
    ('CG', 'Congo-Brazzaville', '+242', 'USD', false),
    ('CD', 'DR Congo', '+243', 'USD', false),
    ('CF', 'Central African Republic', '+236', 'USD', false),
    ('TD', 'Chad', '+235', 'USD', false),
    ('GQ', 'Equatorial Guinea', '+240', 'USD', false),
    ('AO', 'Angola', '+244', 'USD', false),
    ('ZM', 'Zambia', '+260', 'USD', false),
    ('ZW', 'Zimbabwe', '+263', 'USD', false),
    ('BW', 'Botswana', '+267', 'USD', false),
    ('MZ', 'Mozambique', '+258', 'USD', false),
    ('NA', 'Namibia', '+264', 'USD', false),
    ('MW', 'Malawi', '+265', 'USD', false),
    ('RW', 'Rwanda', '+250', 'USD', false),
    ('BI', 'Burundi', '+257', 'USD', false),
    ('SO', 'Somalia', '+252', 'USD', false),
    ('DJ', 'Djibouti', '+253', 'USD', false),
    ('ER', 'Eritrea', '+291', 'USD', false),
    ('SZ', 'Eswatini', '+268', 'USD', false),
    ('LS', 'Lesotho', '+266', 'USD', false),
    ('MG', 'Madagascar', '+261', 'USD', false),
    ('MU', 'Mauritius', '+230', 'USD', false),
    ('SC', 'Seychelles', '+248', 'USD', false),
    ('CV', 'Cabo Verde', '+238', 'USD', false),
    ('GM', 'Gambia', '+220', 'USD', false),
    ('GN', 'Guinea', '+224', 'USD', false),
    ('SL', 'Sierra Leone', '+232', 'USD', false),
    ('LR', 'Liberia', '+231', 'USD', false),
    ('KM', 'Comoros', '+269', 'USD', false),
    ('ST', 'Sao Tome and Principe', '+239', 'USD', false),
    ('MR', 'Mauritania', '+222', 'USD', false),
    ('MX', 'Mexico', '+52', 'USD', false),
    ('BR', 'Brazil', '+55', 'USD', false),
    ('AR', 'Argentina', '+54', 'USD', false),
    ('CL', 'Chile', '+56', 'USD', false),
    ('CO', 'Colombia', '+57', 'USD', false),
    ('PE', 'Peru', '+51', 'USD', false),
    ('EC', 'Ecuador', '+593', 'USD', false),
    ('UY', 'Uruguay', '+598', 'USD', false),
    ('PY', 'Paraguay', '+595', 'USD', false),
    ('BO', 'Bolivia', '+591', 'USD', false),
    ('VE', 'Venezuela', '+58', 'USD', false),
    ('GY', 'Guyana', '+592', 'USD', false),
    ('SR', 'Suriname', '+597', 'USD', false),
    ('GT', 'Guatemala', '+502', 'USD', false),
    ('HN', 'Honduras', '+504', 'USD', false),
    ('NI', 'Nicaragua', '+505', 'USD', false),
    ('CR', 'Costa Rica', '+506', 'USD', false),
    ('PA', 'Panama', '+507', 'USD', false),
    ('SV', 'El Salvador', '+503', 'USD', false),
    ('DO', 'Dominican Republic', '+1', 'USD', false),
    ('CU', 'Cuba', '+53', 'USD', false),
    ('JM', 'Jamaica', '+1', 'USD', false),
    ('HT', 'Haiti', '+509', 'USD', false),
    ('TT', 'Trinidad and Tobago', '+1', 'USD', false),
    ('BS', 'Bahamas', '+1', 'USD', false),
    ('BB', 'Barbados', '+1', 'USD', false),
    ('BZ', 'Belize', '+501', 'USD', false),
    ('LC', 'Saint Lucia', '+1', 'USD', false),
    ('GD', 'Grenada', '+1', 'USD', false),
    ('VC', 'Saint Vincent and the Grenadines', '+1', 'USD', false),
    ('AG', 'Antigua and Barbuda', '+1', 'USD', false),
    ('DM', 'Dominica', '+1', 'USD', false),
    ('KN', 'Saint Kitts and Nevis', '+1', 'USD', false),
    ('CA', 'Canada', '+1', 'CAD', false),
    ('AU', 'Australia', '+61', 'AUD', false),
    ('NZ', 'New Zealand', '+64', 'USD', false),
    ('FJ', 'Fiji', '+679', 'USD', false),
    ('PG', 'Papua New Guinea', '+675', 'USD', false),
    ('WS', 'Samoa', '+685', 'USD', false),
    ('TO', 'Tonga', '+676', 'USD', false),
    ('VU', 'Vanuatu', '+678', 'USD', false),
    ('SB', 'Solomon Islands', '+677', 'USD', false),
    ('KI', 'Kiribati', '+686', 'AUD', false),
    ('TV', 'Tuvalu', '+688', 'AUD', false),
    ('NR', 'Nauru', '+674', 'AUD', false),
    ('FM', 'Micronesia', '+691', 'USD', false),
    ('MH', 'Marshall Islands', '+692', 'USD', false),
    ('PW', 'Palau', '+680', 'USD', false);
