// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddCouponTarget(projectID: string, couponID: string, subjectType: string, subjectID: string): $CancellablePromise<void> {
    return $Call.ByID(2600166677, projectID, couponID, subjectType, subjectID);
}

export function CreateAddon(projectID: string, input: $models.AddonInput): $CancellablePromise<void> {
    return $Call.ByID(2240975083, projectID, input);
}

export function CreateCoupon(projectID: string, input: $models.CouponInput): $CancellablePromise<void> {
    return $Call.ByID(3002421989, projectID, input);
}

export function CreateFeature(projectID: string, input: $models.FeatureInput): $CancellablePromise<void> {
    return $Call.ByID(3771005179, projectID, input);
}

export function CreatePlan(projectID: string, input: $models.PlanInput): $CancellablePromise<void> {
    return $Call.ByID(2375624800, projectID, input);
}

export function DeleteAddon(projectID: string, addonID: string): $CancellablePromise<void> {
    return $Call.ByID(3518790178, projectID, addonID);
}

export function DeleteAddonFeature(projectID: string, addonID: string, featureID: string): $CancellablePromise<void> {
    return $Call.ByID(963922548, projectID, addonID, featureID);
}

export function DeleteCoupon(projectID: string, code: string): $CancellablePromise<void> {
    return $Call.ByID(4152034806, projectID, code);
}

export function DeleteFeature(projectID: string, featureID: string): $CancellablePromise<void> {
    return $Call.ByID(262090442, projectID, featureID);
}

export function DeletePlan(projectID: string, planID: string): $CancellablePromise<void> {
    return $Call.ByID(574668719, projectID, planID);
}

export function DeletePlanFeature(projectID: string, planID: string, featureID: string): $CancellablePromise<void> {
    return $Call.ByID(3040078739, projectID, planID, featureID);
}

export function ListAddonFeatures(projectID: string, addonID: string): $CancellablePromise<$models.AddonFeature[] | null> {
    return $Call.ByID(2688165156, projectID, addonID);
}

export function ListAddons(projectID: string): $CancellablePromise<$models.Addon[] | null> {
    return $Call.ByID(617069352, projectID);
}

export function ListCouponTargets(projectID: string, couponID: string): $CancellablePromise<$models.CouponTarget[] | null> {
    return $Call.ByID(3852158849, projectID, couponID);
}

export function ListCoupons(projectID: string): $CancellablePromise<$models.Coupon[] | null> {
    return $Call.ByID(4084158338, projectID);
}

export function ListFeatures(projectID: string): $CancellablePromise<$models.Feature[] | null> {
    return $Call.ByID(895401720, projectID);
}

export function ListPlanFeatures(projectID: string, planID: string): $CancellablePromise<$models.PlanFeature[] | null> {
    return $Call.ByID(3708250727, projectID, planID);
}

export function ListPlans(projectID: string): $CancellablePromise<$models.Plan[] | null> {
    return $Call.ByID(478967369, projectID);
}

export function RemoveCouponTarget(projectID: string, couponID: string, subjectType: string, subjectID: string): $CancellablePromise<void> {
    return $Call.ByID(33615956, projectID, couponID, subjectType, subjectID);
}

export function UpdateAddon(projectID: string, addonID: string, input: $models.AddonInput): $CancellablePromise<void> {
    return $Call.ByID(1267350776, projectID, addonID, input);
}

export function UpdateCoupon(projectID: string, code: string, input: $models.CouponInput): $CancellablePromise<void> {
    return $Call.ByID(1195949728, projectID, code, input);
}

export function UpdateFeature(projectID: string, featureID: string, input: $models.FeatureInput): $CancellablePromise<void> {
    return $Call.ByID(3638590896, projectID, featureID, input);
}

export function UpdatePlan(projectID: string, planID: string, input: $models.PlanInput): $CancellablePromise<void> {
    return $Call.ByID(3286702645, projectID, planID, input);
}

export function UpsertAddonFeature(projectID: string, addonID: string, input: $models.AddonFeatureInput): $CancellablePromise<void> {
    return $Call.ByID(1425064924, projectID, addonID, input);
}

export function UpsertPlanFeature(projectID: string, planID: string, input: $models.PlanFeatureInput): $CancellablePromise<void> {
    return $Call.ByID(1425906155, projectID, planID, input);
}
