// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function TestDatabase(dsn: string): $CancellablePromise<void> {
    return $Call.ByID(1963094079, dsn);
}

export function TestMQ(dsn: string): $CancellablePromise<void> {
    return $Call.ByID(3404054996, dsn);
}

export function TestRedis(dsn: string): $CancellablePromise<void> {
    return $Call.ByID(2444768209, dsn);
}
