// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Addon {
  id: string
  name: string
  description: string
  prices: string
  active: boolean
  created_at: string
}

export interface AddonFeature {
  addon_id: string
  feature_id: string
  limit_value: number | null
}

export interface AddonFeatureInput {
  feature_id: string
  limit_value: number | null
}

export interface AddonInput {
  id: string
  name: string
  description: string
  prices: string
  active: boolean
}

export interface AtRiskInvoice {
  invoice_id: string
  organization_id: string
  organization_name: string
  organization_slug: string
  amount_cents: number
  currency: string
  status: string
  created_at: string
  days_pending: number
}

export interface AuditEvent {
  id: string
  organization_id: string
  actor: string
  action: string
  resource: string
  status_code: number
  ip: string
  created_at: string
}

export interface AuditFilter {
  actor: string

  /**
   * HTTP method or empty
   */
  action: string
  organization_id: string

  /**
   * 0 = no filter
   */
  status_code: number

  /**
   * RFC3339 or empty
   */
  from: string

  /**
   * RFC3339 or empty
   */
  to: string
  limit: number
  offset: number
}

export interface BroadcastInput {
  title: string
  body: string

  /**
   * "all" | "organization:<uuid>" | "user:<auth_sub>"
   */
  target: string
}

export interface BroadcastLog {
  id: number
  title: string
  body: string
  target: string
  recipient_count: number
  sent_at: string
}

export interface ComponentStatus {
  postgres: string
  redis: string
  rabbitmq: string
}

export interface Country {
  code: string
  name: string
  phone_code: string
  currency_code: string
  tax_rate_bps: number
  active: boolean
}

export interface CountryInput {
  code: string
  name: string
  phone_code: string
  currency_code: string
  tax_rate_bps: number
  active: boolean
}

export interface Coupon {
  code: string
  name: string
  discount_type: string
  amount_cents: number | null
  percent_off: number | null
  currency: string
  cadence: string
  duration_count: number | null
  valid_from: string
  valid_until: string
  max_redemptions: number | null
  redeemed_count: number
  metadata: string
  active: boolean
  created_at: string
}

export interface CouponInput {
  code: string
  name: string
  discount_type: string
  amount_cents: number | null
  percent_off: number | null
  currency: string
  cadence: string
  duration_count: number | null
  valid_from: string
  valid_until: string
  max_redemptions: number | null
  metadata: string
  active: boolean
}

export interface CouponTarget {
  coupon_id: string
  subject_type: string
  subject_id: string
  created_at: string
}

export interface Currency {
  code: string
  name: string
  symbol: string
  decimal_places: number
  active: boolean
}

export interface CurrencyInput {
  code: string
  name: string
  symbol: string
  decimal_places: number
  active: boolean
}

export interface DBPoolStats {
  total_conns: number
  idle_conns: number
  acquired_conns: number
  max_conns: number
}

export interface DLQInfo {
  name: string
  messages: number
  consumers: number
  state: string

  /**
   * messages/sec (incoming publish rate)
   */
  message_rate: number
}

export interface DLQMessage {
  routing_key: string
  exchange: string
  body: string
  body_bytes: number
  redelivered: boolean
}

export interface Feature {
  id: string
  name: string
  description: string
  type: string
  metric_key: string
  active: boolean
  created_at: string
}

export interface FeatureInput {
  id: string
  name: string
  description: string
  type: string
  metric_key: string
  active: boolean
}

export interface HealthStatus {
  /**
   * "ok" | "degraded" | "down"
   */
  status: string

  /**
   * -1 when unreachable
   */
  latency_ms: number
  checked_at: string
  message: string
  components: ComponentStatus
  stats?: RuntimeStats | null
}

export interface MemoryStats {
  heap_alloc_bytes: number
  heap_sys_bytes: number
  stack_in_use_bytes: number
  gc_runs: number
  gc_cpu_fraction: number
}

export interface MonitorLog {
  id: number
  project_id: string
  status: string
  latency_ms: number | null
  checked_at: string
  components: ComponentStatus
  stats?: RuntimeStats | null
}

export interface OperatorLogEntry {
  id: number
  project_id: string
  project_name: string
  action: string
  target_id: string
  detail: string
  performed_at: string
}

export interface OrganizationSummary {
  id: string
  name: string
  slug: string
  status: string
  country_code: string
  owner_id: string
  created_at: string
  member_count: number
  plan_name: string
  billing_status: string
}

export interface Plan {
  id: string
  name: string
  description: string
  prices: string
  sort_order: number
  active: boolean
  created_at: string
  updated_at: string
}

export interface PlanCount {
  plan: string
  count: number
}

export interface PlanFeature {
  plan_id: string
  feature_id: string
  limit_value: number | null
  config_value: string
}

export interface PlanFeatureInput {
  feature_id: string
  limit_value: number | null
  config_value: string
}

export interface PlanInput {
  id: string
  name: string
  description: string
  prices: string
  sort_order: number
  active: boolean
}

export interface Project {
  id: string
  name: string
  api_url: string
  db_dsn: string
  mq_dsn: string
  redis_dsn: string
  stats_token: string
  color: string
  created_at: string
  last_seen_at: string | null
}

export interface ProjectInput {
  name: string
  api_url: string
  db_dsn: string
  mq_dsn: string
  redis_dsn: string
  stats_token: string
  color: string
}

export interface ProjectMetrics {
  total_organizations: number
  active_organizations: number
  total_members: number
  subscriptions_by_status: SubscriptionStatus[] | null
  mrr: number
  arr: number
  new_organizations_last_30d: number
  storage_bytes_total: number
  top_plans_by_organization: PlanCount[] | null
}

export interface RedisPoolStats {
  total_conns: number
  idle_conns: number
  hits: number
  misses: number
}

/**
 * RequeueResult reports the outcome of RequeueMessage. When Requeued is false,
 * Lost holds the message that was consumed from the DLQ but never made it back
 * onto its exchange — the operator's only remaining record of it — and Error
 * explains why the republish failed.
 */
export interface RequeueResult {
  requeued: boolean
  lost?: DLQMessage | null
  error?: string
}

export interface RuntimeStats {
  uptime_seconds: number
  num_cpu: number
  goroutines: number
  memory: MemoryStats
  db_pool: DBPoolStats
  redis_pool?: RedisPoolStats | null
}

export interface SubscriptionStatus {
  status: string
  count: number
}

export interface UserDetail {
  auth_sub: string
  full_name: string
  email: string
  avatar_url: string
  last_seen_at: string | null
  organizations: UserOrganization[] | null
}

export interface UserInvoice {
  id: string
  amount_cents: number
  currency: string
  status: string
  created_at: string
  paid_at: string | null
}

export interface UserLoginEvent {
  ip_address: string
  user_agent: string
  created_at: string
}

export interface UserOrganization {
  id: string
  name: string
  slug: string
  status: string
  role: string
  plan: string
  plan_name: string
  billing_status: string
  trial_end: string | null
  period_end: string | null
}

export interface UserResult {
  auth_sub: string
  full_name: string
  email: string
  avatar_url: string
  last_seen_at: string | null
}

export interface WatchlistItem {
  organization_id: string
  organization_name: string
  organization_slug: string
  plan_name: string
  status: string
  trial_end: string | null
  period_end: string | null
  days_remaining: number
}

export interface WatchlistResult {
  trials_ending_soon: WatchlistItem[] | null
  past_due: WatchlistItem[] | null
  renewals_due: WatchlistItem[] | null
  cancellations_pending: WatchlistItem[] | null
}
