// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {
  Call as $Call,
  CancellablePromise as $CancellablePromise,
} from "@wailsio/runtime"

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js"

export function Add(
  input: $models.ProjectInput
): $CancellablePromise<$models.Project> {
  return $Call.ByID(2504231096, input)
}

export function Delete(id: string): $CancellablePromise<void> {
  return $Call.ByID(2254368086, id)
}

export function Get(id: string): $CancellablePromise<$models.Project> {
  return $Call.ByID(625733235, id)
}

export function List(): $CancellablePromise<$models.Project[] | null> {
  return $Call.ByID(3197347053)
}

export function Update(
  id: string,
  input: $models.ProjectInput
): $CancellablePromise<$models.Project> {
  return $Call.ByID(1652088448, id, input)
}
