// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {
  Call as $Call,
  CancellablePromise as $CancellablePromise,
} from "@wailsio/runtime"

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js"

/**
 * GetAll returns all four watchlist buckets in a single call.
 */
export function GetAll(
  projectID: string
): $CancellablePromise<$models.WatchlistResult> {
  return $Call.ByID(165011160, projectID)
}
