package events_test

import (
	"context"
	"encoding/json"
	"os"
	"reflect"
	"testing"
	"time"
	"uuid"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/aasumitro/stratum/internal/contracts/events"
	"github.com/aasumitro/stratum/internal/platform/messaging"
)

// capturingPublisher records the last published envelope body instead of
// sending it anywhere, so a test can inspect what Publish/PublishDelayed
// actually construct without a broker in this binary — same pattern
// internal/modules/billing and internal/modules/organization already use
// in their own test packages.
type capturingPublisher struct {
	body []byte
}

func (p *capturingPublisher) Publish(_ context.Context, _, _ string, body []byte) error {
	p.body = body
	return nil
}

func (p *capturingPublisher) PublishDelayed(_ context.Context, _, _ string, body []byte, _ time.Duration) error {
	p.body = body
	return nil
}

var _ messaging.EventPublisher = (*capturingPublisher)(nil)

func TestEnvelopeID_ReadsIDWithoutDecodingData(t *testing.T) {
	body := []byte(`{"id":"evt-123","type":"org.created","source":"organization","data":{"anything":"goes here"}}`)

	id, err := events.EnvelopeID(body)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if id != "evt-123" {
		t.Errorf("EnvelopeID = %q, want %q", id, "evt-123")
	}
}

func TestEnvelopeID_MalformedBody_Errors(t *testing.T) {
	if _, err := events.EnvelopeID([]byte("not json")); err == nil {
		t.Fatal("expected an error for malformed JSON, got nil")
	}
}

func TestEnvelopeID_MissingID_ReturnsEmptyNoError(t *testing.T) {
	id, err := events.EnvelopeID([]byte(`{"type":"org.created"}`))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if id != "" {
		t.Errorf("EnvelopeID = %q, want empty", id)
	}
}

// TestPublish_GeneratesUUIDv7 calls the real Publish and decodes the
// envelope it actually constructs, rather than asserting on the uuid
// library directly, so a regression in Envelope.ID's generation (e.g.
// swapping uuid.NewV7() for plain uuid.New(), which produces v4) is
// caught through the same path every real caller uses.
func TestPublish_GeneratesUUIDv7(t *testing.T) {
	pub := &capturingPublisher{}
	events.Publish(context.Background(), pub, events.ExchangeOrganization, "org.created",
		"organization", "org-1", map[string]string{"k": "v"})

	id := decodeEnvelopeID(t, pub.body)
	if v := uuidVersion(id); v != 7 {
		t.Errorf("envelope ID version = %d, want 7 (uuidv7)", v)
	}
}

// TestPublishDelayed_GeneratesUUIDv7 is TestPublish_GeneratesUUIDv7's
// counterpart for the second uuid.New() call site envelope.go had —
// PublishDelayed builds its own Envelope independently of Publish.
func TestPublishDelayed_GeneratesUUIDv7(t *testing.T) {
	pub := &capturingPublisher{}
	events.PublishDelayed(context.Background(), pub, events.ExchangeBillingDelay, "billing.retry",
		"billing", "org-1", map[string]string{"k": "v"}, time.Minute)

	id := decodeEnvelopeID(t, pub.body)
	if v := uuidVersion(id); v != 7 {
		t.Errorf("envelope ID version = %d, want 7 (uuidv7)", v)
	}
}

func testPool(t *testing.T) *pgxpool.Pool {
	t.Helper()
	dsn := os.Getenv("TEST_DATABASE_URL")
	if dsn == "" {
		t.Skip("TEST_DATABASE_URL not set")
	}
	pool, err := pgxpool.New(t.Context(), dsn)
	if err != nil {
		t.Fatalf("open pool: %v", err)
	}
	t.Cleanup(pool.Close)
	return pool
}

// TestIntegration_Enqueue_RoundTripsSamePayloadAsPublish inserts an outbox
// row via Enqueue inside a real transaction, then asserts the row's payload
// unmarshals to the identical Envelope Publish would have produced for the
// same inputs (modulo the ID/Time fields, which are freshly generated by
// each call) — proving Enqueue's outbox row is a faithful stand-in for a
// direct broker publish, the whole premise the relay depends on.
func TestIntegration_Enqueue_RoundTripsSamePayloadAsPublish(t *testing.T) {
	pool := testPool(t)
	data := map[string]string{"k": "v"}

	tx, err := pool.Begin(t.Context())
	if err != nil {
		t.Fatalf("begin tx: %v", err)
	}
	defer func() { _ = tx.Rollback(context.Background()) }()

	if err := events.Enqueue(t.Context(), tx, events.ExchangeOrganization,
		"org.created", "organization", "org-1", data); err != nil {
		t.Fatalf("Enqueue: %v", err)
	}

	var payload []byte
	err = tx.QueryRow(t.Context(),
		`SELECT payload FROM messaging.outbox WHERE routing_key = 'org.created' AND exchange = $1`,
		events.ExchangeOrganization,
	).Scan(&payload)
	if err != nil {
		t.Fatalf("query outbox row: %v", err)
	}

	// Publish (against a capturing publisher, no real broker) builds the
	// same shape of Envelope for the same inputs — decode both and compare
	// everything except ID/Time, which each call generates fresh.
	pub := &capturingPublisher{}
	events.Publish(t.Context(), pub, events.ExchangeOrganization, "org.created", "organization", "org-1", data)

	var enqueued, published struct {
		Type   string            `json:"type"`
		Source string            `json:"source"`
		OrgID  string            `json:"org_id"`
		Data   map[string]string `json:"data"`
	}
	if err := json.Unmarshal(payload, &enqueued); err != nil {
		t.Fatalf("unmarshal enqueued payload: %v", err)
	}
	if err := json.Unmarshal(pub.body, &published); err != nil {
		t.Fatalf("unmarshal published payload: %v", err)
	}
	if !reflect.DeepEqual(enqueued, published) {
		t.Errorf("Enqueue's outbox payload = %+v, want it to match Publish's envelope shape %+v", enqueued, published)
	}

	id := decodeEnvelopeID(t, payload)
	if v := uuidVersion(id); v != 7 {
		t.Errorf("outbox row's envelope ID version = %d, want 7 (uuidv7)", v)
	}
}

// TestIntegration_EnqueueDelayed_SetsFutureNotBefore proves EnqueueDelayed
// folds delay into not_before rather than a separate mechanism — the
// relay's claimUnpublished query relies on this to unify "publish now" and
// "publish later" into one WHERE clause.
func TestIntegration_EnqueueDelayed_SetsFutureNotBefore(t *testing.T) {
	pool := testPool(t)

	tx, err := pool.Begin(t.Context())
	if err != nil {
		t.Fatalf("begin tx: %v", err)
	}
	defer func() { _ = tx.Rollback(context.Background()) }()

	if err := events.EnqueueDelayed(t.Context(), tx, events.ExchangeBillingDelay,
		"billing.retry", "billing", "org-1", map[string]string{"k": "v"}, time.Hour); err != nil {
		t.Fatalf("EnqueueDelayed: %v", err)
	}

	var notBefore, createdAt time.Time
	err = tx.QueryRow(t.Context(),
		`SELECT not_before, created_at FROM messaging.outbox WHERE routing_key = 'billing.retry'`,
	).Scan(&notBefore, &createdAt)
	if err != nil {
		t.Fatalf("query outbox row: %v", err)
	}
	if !notBefore.After(createdAt.Add(59 * time.Minute)) {
		t.Errorf("not_before = %v, want at least ~1h after created_at %v", notBefore, createdAt)
	}
}

func decodeEnvelopeID(t *testing.T, body []byte) uuid.UUID {
	t.Helper()
	var env struct {
		ID string `json:"id"`
	}
	if err := json.Unmarshal(body, &env); err != nil {
		t.Fatalf("unmarshal published envelope: %v", err)
	}
	id, err := uuid.Parse(env.ID)
	if err != nil {
		t.Fatalf("parse envelope ID %q: %v", env.ID, err)
	}
	return id
}

// uuidVersion extracts the RFC 9562 version number — the high nibble of
// octet 6. stdlib uuid.UUID (unlike github.com/google/uuid) exposes no
// Version() accessor.
func uuidVersion(u uuid.UUID) int { return int(u[6] >> 4) }
